### ISSUE TITLE
Error: No Variables in your Function

### ISSUE THREAD

**Issue by ejmeitz** [brianguenter/FastDifferentiation.jl#54]
I have the code below which works, but if I make a minor modification things break when taking the `hessian`. Specifically, I get an error that there are no variables in your function. Is this something you've seen before? If not I can get a MWE again. Thanks!

THIS CODE WORKS:
```julia
D = 3
r_ij_vars = make_variables(:rij, D)

r_ij_norm = sqrt(sum(x -> x^2, r_ij_vars))
    
#2nd order part 
pot2_symbolic = pair_potential_nounits(pot, r_ij_norm)
H2_symbolic = hessian(pot2_symbolic, r_ij_vars) 
H2_exec = make_function(H2_symbolic, r_ij_vars)
```

THIS CODE DOES NOT:
```julia
D = 3
r_i_vars = make_variables(:ri, D)
r_j_vars = make_variables(:rj, D)

r_ij_vars = r_i_vars .- r_j_vars

r_ij_norm = sqrt(sum(x -> x^2, r_ij_vars))
    
#2nd order part 
pot2_symbolic = pair_potential_nounits(pot, r_ij_norm)
H2_symbolic = hessian(pot2_symbolic, r_ij_vars)  #Error here
H2_exec = make_function(H2_symbolic, r_ij_vars)
```

**Comment by brianguenter** [comment]
That error occurs when there are no variables in your function. In this case it would trigger if your function is all constants, or the jacobian of your function is all constants.

If you send me a working executable MWE I should be able to track this down quickly.

It might be better for FastDifferentiation to return an all zero matrix rather than throwing an exception. I'll think about it and make the change today if it doesn't introduce problems in other parts of the code.

**Comment by ejmeitz** [comment]
Copied the functions you'd need below to run the code I copied above. The thing I don't get is why FastDiff works fine in the one path but not in the other. It should be identical from a math point of view. In the first code I define a set of variables r_ij and in the second code I calculate those variables from a set of other variables. Maybe this is not allowed in FastDiff at the moment, but I do not immediately see why it shouldnt work.

```julia

struct SW_Params{E,S}
    ϵ::E #ep has energy units
    σ::S #simga has length units
    a::Float64 #cutoff = a*sigma
    λ::Float64
    γ::Float64
    cosθ₀::Float64
    A::Float64
    B::Float64
    p::Float64
    q::Float64
end

function SW_Params(ϵ, σ, a, λ, γ, cosθ₀, A, B , p, q)
    return SW_Params{typeof(ϵ), typeof(σ)}(ϵ, σ, a, λ, γ, cosθ₀,
                                             A, B , p, q)
end

struct StillingerWeberSilicon{R,L,E,GS,LE} <: ThreeBodyPotential
    r_cut::R
    length_unit::L
    energy_unit::E
    params::SW_Params
    gamma_sigma::GS
    lambda_epsilon::LE
end


function StillingerWeberSilicon()
    #From LAMMPS Si.sw file
    sws_params = SW_Params(2.1683u"eV", 2.0951u"Å", 1.80, 21.0, 1.20,
        -0.333333333333, 7.049556277,  0.6022245584,  4.0,  0.0)
    
    r_cut = sws_params.a*sws_params.σ
    length_unit = unit(sws_params.σ)
    energy_unit = unit(sws_params.ϵ)
    gamma_sigma = sws_params.σ*sws_params.γ
    lambda_epsilon = sws_params.ϵ*sws_params.λ

    return StillingerWeberSilicon{typeof(r_cut),typeof(length_unit),typeof(energy_unit), typeof(gamma_sigma), typeof(lambda_epsilon)}(
                r_cut, length_unit, energy_unit, sws_params, gamma_sigma, lambda_epsilon)
end

function pair_potential_nounits(pot::StillingerWeberSilicon, dist_ij)   
    return Φ₂(pot.params.A, pot.params.B, ustrip(pot.params.ϵ), ustrip(pot.params.σ),
                 pot.params.p, pot.params.q, pot.params.a, dist_ij)
end

function Φ₂(A, B, ϵ, σ, p, q, a, rᵢⱼ)
    return A*ϵ*(B*((σ/rᵢⱼ)^p) - ((σ/rᵢⱼ)^q)) * exp(σ/(rᵢⱼ-(a*σ)))
end

pot = StillingerWeberSilicon()
```

**Comment by brianguenter** [comment]
FastDifferentiation does not currently allow taking derivatives with respect to internal nodes of the function graph. You can do this
```julia
derivative(x^2+y^2,[x,y])
```
but if you do this 
```julia
derivative(x^2 + y^2, [x-y])
```
FastDifferentiation will compute the derivative with respect to `x-y` as being identically zero.

In your case this line:
```julia
H2_symbolic = hessian(pot2_symbolic, r_ij_vars)
```
is taking the second derivative wrt an internal graph node `ri-rj` rather than a leaf variable node. Since your "variable" is not a leaf of the function graph the derivative with respect to it is currently computed as identically zero.

Your first example computes a different derivative since you explicitly construct all the `r_ij` as variable nodes.

I plan to add the ability to take the derviative wrt non-leaf graph nodes but have some longstanding bugs to fix before I add more features.

Your example did, however, highlight a bug which occurred when creating a function without variables and then attempting to compute derivatives. That was the error message you saw. I've fixed this bug and will be updating the code to the Julia registry soon.

**Comment by brianguenter** [comment]
If this addresses your problem let me know and I'll close theissue.

**Comment by ejmeitz** [comment]
Yep, it all makes sense I'll have to just re write my code I guess.

Thanks!
