### ISSUE TITLE
would it make sense to have FastDifferentiation.Node <: Real?

### ISSUE THREAD

**Issue by tpapp** [brianguenter/FastDifferentiation.jl#73]
Currently functions that restrict their type argument to `::Real` scalars will not accept `Node` arguments, even if the algorithm would work. Do you need the full generality of `Number` for this package?

**Comment by brianguenter** [comment]
Currently `Number` is not strictly necessary. I had visions of supporting differentiation of functions of complex numbers in which case `Real` would be too restrictive. But complex derivatives may never happen, or at least are far in the future.

As a test I changed the definition to be `Node <: Real` instead of `Node <: Number`. Several obscure errors popped up, deep in Julia Base. Hashing no longer works properly because there is no `decompose` function defined for `Node`, whatever the `decompose` function does. Looks like this is an optimization to make hashing faster for `Real` types. In addition, for obscure reasons the comparison operators `<`, `>`, etc., are assumed to apply to `Node` objects.

Probably several days to fix these problems, assuming there is a simple fix.

Do many of the optimization/numerical packages in Julia restrict argument types to `::Real`? If this is a problem most people would encounter then I'd seriously consider making the change, and deal with complex numbers if and when I add that feature.

**Comment by brianguenter** [comment]
@tpapp did you have an opinion on this? As I said if this is a common problem I can switch from `Number` to `Real`.

**Comment by tpapp** [comment]
Currently if you have functions that accept `::Real` arguments, they require a different type signature to work with this package. This may or may not be feasible, as a lot of functions in packages restrict to `::Real`. This has been working fine with overloading AD packages, eg `ForwardDiff.Dual <: Real`.

So, if changing `Number` to `Real` as a supertype is feasible, I think it would be desirable.

**Comment by brianguenter** [comment]
Ok, I'll look at it more closely. Will probably take a week or so since I've got a couple of other issues to finish up.

**Comment by brianguenter** [comment]
I haven't forgotten this. I'm working my way through several previously reported bugs, will work on this afterward.

**Comment by tpapp** [comment]
Thanks, no pressure.

**Comment by brianguenter** [comment]
It turned out this was actually trivial to fix. CI for the fix is running. If everything works then I'll make a new patch release.

**Comment by brianguenter** [comment]
unfortunately the patch version 0.3.16 did not pick up the code to actually make this patch. I'm going to release a new patch 0.3.17, which should have the fix.

**Comment by tpapp** [comment]
thanks!
